spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-53y3z1sl4000gi2o.rwlb.rds.aliyuncs.com:3306/smart_course
    username: root
    password: Gu123456


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
