spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-53y3z1sl4000gi2o.rwlb.rds.aliyuncs.com:3306/smart_course
    username: root
    password: Gu123456


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: your-access-key-id
    accessKeySecret: your-access-key-secret
    bucketName: your-bucket-name
